import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,RULES} from '../dist/engine.js';
import {TOOLS,DAYS} from '../dist/data.js';

test('nine guests each have all five evidence channels',()=>{assert.equal(DAYS.flatMap(d=>d.guests).length,9);for(const d of DAYS)for(const e of d.guests){assert.equal(Object.keys(e.clues).length,5);assert.ok(e.quote.length>10);}});
test('packed tools own real cells, movement and rotation respect collisions',()=>{const g=new Game();assert.equal(g.bag.reduce((n,e)=>n+e.w*e.h,0),5);const scale=g.bag.find(e=>e.id==='scale');assert.throws(()=>g.move(scale.uid,0,0));assert.throws(()=>g.move(scale.uid,3,2));g.move(scale.uid,0,1,true);assert.equal(g.at(0,2).uid,scale.uid);assert.throws(()=>g.move(scale.uid,1.5,1));});
test('tools lock during service, duplicated inspection is free, max three checks',()=>{const g=new Game();g.equip('registry');g.open();assert.throws(()=>g.equip('lens'));g.inspect('lens');g.inspect('lens');assert.equal(g.actions,2);g.inspect('scale');g.inspect('geiger');assert.throws(()=>g.inspect('registry'));assert.equal(g.proofs.length,3);});
test('acid cost and damage persist through purchase and sale',()=>{const g=new Game();g.equip('acid');g.open();g.inspect('acid');g.inspect('acid');assert.equal(g.money,RULES.start-2);g.buy();const e=g.bag.find(e=>e.type==='goods');assert.equal(e.damaged,true);assert.equal(g.quote(e,'caravan','genuine'),24);assert.equal(g.quote(e,'caravan','unverified'),3);});
test('failed purchases cannot pay or skip a guest',()=>{const g=new Game();for(const id of Object.keys(TOOLS))if(!g.has(id))g.equip(id);g.open();g.buy();g.buy();const money=g.money;assert.throws(()=>g.buy());assert.equal(g.money,money);assert.equal(g.guest,2);});
test('fake authenticated sales refund income and add fine only once',()=>{const g=new Game();g.open();g.buy();g.reject();g.reject();const e=g.bag.find(a=>a.type==='goods'),uid=e.uid;g.sell(uid,'caravan','genuine');assert.equal(g.refunds,36);assert.throws(()=>g.sell(uid,'caravan','genuine'));g.settle();assert.equal(g.money,RULES.start-8-6-RULES.daily);assert.throws(()=>g.settle());});
test('clinic gets no benefit from fake certified goods; militia only takes relevant items',()=>{const g=new Game();g.open();g.reject();g.buy();g.reject();const e=g.bag.find(a=>a.type==='goods');assert.ok(!g.routes(e).includes('militia'));assert.throws(()=>g.sell(e.uid,'militia','genuine'));g.sell(e.uid,'clinic','genuine');assert.equal(g.aid,1);});
test('public evidence requires both the lens and radiation readings',()=>{const g=new Game();g.equip('scale');g.day=2;g.open();g.inspect('lens');g.buy();g.reject();g.reject();const e=g.bag.find(a=>a.type==='goods');assert.ok(!g.routes(e).includes('public'));assert.throws(()=>g.sell(e.uid,'public'));g.settle();assert.equal(g.health,80);});
test('mid-inspection save reload retains inventory, proof and costs',()=>{const g=new Game();g.open();g.inspect('lens');const copy=Game.load(g.save());assert.ok(copy);assert.equal(copy.actions,2);assert.deepEqual(copy.proofs,['lens']);assert.equal(copy.has('scale'),true);assert.equal(Game.load('bad'),null);assert.equal(Game.load(JSON.stringify({version:1,state:{day:99}})),null);});
function campaign(target){const g=new Game();g.equip('scale');for(let d=0;d<3;d++){g.open();for(let i=0;i<3;i++){const c=g.current;g.inspect('lens');g.inspect('geiger');let buy=c.real&&!c.hazard;if(target==='debt')buy=false;if(target==='candle')buy=['filter','chalice','relay','manual'].includes(c.id);if(target==='light'&&c.id==='leadbox')buy=true;if(buy){try{g.buy();}catch{g.reject();}}else g.reject();}for(const e of [...g.bag]){if(e.type!=='goods')continue;let route='caravan';if(target==='light'){if(e.kind==='medical')route='clinic';if(e.kind==='core')route='public';}if(target==='war'&&e.kind==='dual')route='militia';if(target==='archive')route='abbey';g.sell(e.uid,route,'genuine');}g.settle();if(g.phase==='ending')break;g.tomorrow();}return g;}
for(const target of ['light','war','archive','debt','road','candle'])test(`complete three-day route: ${target}`,()=>{const g=campaign(target);console.log(`${target}: ${g.ending}, money ${g.money}, aid ${g.aid}, war ${g.war}, archive ${g.archive}`);assert.equal(g.ending,target);assert.equal(g.phase,'ending');});
